---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: auto

platforms:
  - name: gannett/gci-centos-67
  - name: gannett/gci-centos-72

suites:
  - name: default
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[datadog]
      - recipe[tyk_support::default]
      - recipe[tyk_support::tyk-redis-monitor]
    attributes:
      datadog:
        redis-tyk:
          instances:
            - host: 'localhost'
              port: '6379'
              tags: ['redis-tyk-test']
    chef_client:
      config:
        log_level: ":debug"
